### ISSUE TITLE
Set up project structure 

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/hector-calibration-summer-2024#2]
* Add the .Rpoj file & then add it to .gitignore 
* Create a the subdirectory folders such as `comparison_data`, `scripts`, `results` (in order to add to git there is going to need to be some sort of file in each directory if you don't have anything to add yet add a readme.md file that has a brief description of what the directory will eventually contain)

**Comment by ptrscll** [comment]
I didn't mean to close the issue before the PR was approved, my bad.
