### ISSUE TITLE
Ocean Heat Content

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/hector-calibration-summer-2024#26]
**Source:** Kuhlbrodt, T., A. Voldoire, M. D. Palmer, O. Geoffroy, and R. E. Killick, 2023: Historical Ocean Heat Uptake in Two Pairs of CMIP6 Models: Global and Regional Perspectives. J. Climate, 36, 2183–2203, https://doi.org/10.1175/JCLI-D-22-0468.1.

The [SI zip file](https://journals.ametsoc.org/view/journals/clim/36/7/JCLI-D-22-0468.1.xml?tab_body=supplementary-materials) has ocean heat content that I would like to compare with Hector results 

I think it is going to be - OHC_ensemble_Kuhlbrodt_etal_2022.csv the Central Estimate Full-depth column. 

It would also be interesting to look at the yearly [world heat content ](https://www.ncei.noaa.gov/access/global-ocean-heat-content/basin_heat_data.html) from NOAA I think a challenge here is the ocean depth

**Comment by ptrscll** [comment]
Their csv file's values are only given for the midpoint of each year (e.g, year 2013.5), so how should I go about calculating ocean heat content for a given year? For example, to calculate the change in ocean heat content from 2012.5 to 2013.5, would it make sense to add half the change in ocean heat content based on the 2012 heat flux to half the change in ocean heat content based on the 2013 heat flux? Or would it be better to just add the full change in ocean heat content based just on the heat flux from one of those years?

**Comment by kdorheim** [comment]
For now, since this is just a ballpark comparison let's round down, 2013.5 -> 2013.
