### ISSUE TITLE
Set up and run experiment one

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/hector-calibration-summer-2024#5]
In some ways this is going to be the experiment that let's us verify that that the calibration workflow is working as expected. This will be re-implementing the calibration of beta, q10, and diff that was used in the V3 manuscript.

**Comment by ptrscll** [comment]
I just realized that the CO2 dataset has an end year of 2023 and the temperature dataset has an end year of 2024, but Hector doesn't use historical emissions records for the most recent years, so what year should I use as my end year for calculating MSEs?

Edit: I just checked the manuscript and saw that data was calibrated up to 2021 but that you used a dataset with CO2 concentrations going back to 1850 - should I also be using that dataset?
